### ISSUE TITLE
[Infected] | Ideas/Feedback from Discord

### ISSUE THREAD

**Issue by chsedotsh** [JezuzLizard/T6-Custom-Gamemodes#1]
* Place tac insert in the tactical slot if no tomahawks
* martyrdom infected interaction (survivors suicide trolling others)
* add config for infected martyrdom [deathstreak]
* scavenger overfeeds equipment (3 stuns, etc)
* assign models to infected/survivors
* disable turrets on maps
* juiced
* more default classes
* if someone joins while radar is on (last player) it will remain on when 2+ are humans

---

Done Already:
* ~~Add config for killstreaks/specialists~~
* ~~Add config for last player reveal~~
* ~~add config for 'new players become survivors' grace period~~
* ~~add config for maps:tksetting pair~~

**Comment by callanb** [comment]
Addressed in the recent commit:

- Added configurable last player reveal.
- Added 'new players become survivors' grace period.
- Tomahawk enabled map override list.
- Order of specialists can be configured.
